language: python
python:
  - "2.7"
  - "3.7"
sudo: required
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
addons:
  firefox: 45.8.0esr
env:
  matrix:
    - PLONE_VERSION=4.3.x
    - PLONE_VERSION=5.1.x
    - PLONE_VERSION=5.2.x
jobs:
  exclude:
    - python: "3.7"
      env: PLONE_VERSION=4.3.x
    - python: "3.7"
      env: PLONE_VERSION=5.1.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - pip install -r requirements.txt
  # FIXME: I have no idea how and why six==1.11.0 is being installed
  - pip uninstall -y six
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - buildout -t 10 -c travis.cfg
script:
  - make code-analysis
  - make test-release
  - make test
